version: '3.3'
services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_container
    volumes:
      -  ./php:/var/www/html/
    ports:
      - "8000:80"
  db:
    container_name: mysql
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "6033:3306"
  redis:
    image: redis:6.2-alpine
    volumes:
      - ./data:/data
    ports:
      #- ${REDIS_PORT}:${REDIS_PORT}
      -  6378:6378

